<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>kicad-validate</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/KiCad.Automation.Distribution/KiCad.Automation.Distribution.csproj" />
  </ItemGroup>
</Project>
