<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>kicad-mcp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../KiCad.Automation.Native/KiCad.Automation.Native.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>
</Project>
