<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>kicad-downloads</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/KiCad.Automation.Distribution/KiCad.Automation.Distribution.csproj" />
    <EmbeddedResource Include="Web/**/*" LogicalName="kicad-downloads.Web.%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
