<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:kicad:automation:design:1"
           xmlns="urn:kicad:automation:design:1" elementFormDefault="qualified"
           xmlns:e="urn:kicad:automation:engineering-design:1"
           xmlns:n="urn:kicad:automation:schematic-data:1" xmlns:c="urn:kicad:automation:circuit:1">
  <xs:import namespace="urn:kicad:automation:engineering-design:1"/>
  <xs:import namespace="urn:kicad:automation:schematic-data:1"/>
  <xs:import namespace="urn:kicad:automation:circuit:1"/>
  <xs:element name="design"><xs:complexType><xs:sequence>
    <xs:element ref="e:engineering-design"/><xs:element ref="n:schematic-data"/>
    <xs:element name="sheet-bindings"><xs:complexType><xs:sequence>
      <xs:element name="sheet" minOccurs="0" maxOccurs="unbounded"><xs:complexType><xs:sequence>
        <xs:element name="path-item" minOccurs="1" maxOccurs="unbounded"><xs:complexType>
          <xs:attribute name="id" type="c:identity" use="required"/>
        </xs:complexType></xs:element>
      </xs:sequence><xs:attribute name="model" type="c:identity" use="required"/></xs:complexType></xs:element>
    </xs:sequence></xs:complexType></xs:element>
    <xs:element name="symbol-bindings"><xs:complexType><xs:sequence>
      <xs:element name="symbol" minOccurs="0" maxOccurs="unbounded"><xs:complexType>
        <xs:attribute name="model" type="c:identity" use="required"/>
        <xs:attribute name="native" type="c:identity" use="required"/>
      </xs:complexType></xs:element>
    </xs:sequence></xs:complexType></xs:element>
  </xs:sequence><xs:attribute name="version" type="xs:positiveInteger" use="required" fixed="1"/></xs:complexType></xs:element>
</xs:schema>
